services:

  app:
    build: .
    image: product_image
    container_name: product_container
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/Products
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root


  db:
    image: postgres:16
    environment:
      POSTGRES_DB: Products
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  db-data:
